### ISSUE TITLE
Add a liveblog_example module

### ISSUE THREAD

**Issue by chrfritsch** [galaniprojects/liveblog#76]
It would be better to separate the code from the configuration. 

Please move all the files from config/install besides liveblog.liveblog_post.settings.yml in a dedicated liveblog_example module.

**Comment by goldquest** [comment]
Hmm, I think these configs are pretty vital for the module. They are not an example on how to use it. They define the actual usage of the module.

**Comment by chrfritsch** [comment]
Ok, i see. Without these exact configuration, the module can't work.
