### ISSUE TITLE
Remove everything related to Thunder

### ISSUE THREAD

**Issue by chrfritsch** [galaniprojects/liveblog#77]
This module should not have a dependency on Thunder.

Stuff that is needed to integrate with Thunder should be moved into the distribution.

**Comment by goldquest** [comment]
Yes, I think so too. Where did you see Thunder related stuff for example?

**Comment by chrfritsch** [comment]
liveblog_paragraphs is completed dependent on Thunder

**Comment by goldquest** [comment]
Yes, this is the integration in thunder. Do you want to move it into the distribution?

**Comment by chrfritsch** [comment]
Yes, that should be part of the integration in thunder

**Comment by goldquest** [comment]
fixed by https://github.com/galaniprojects/liveblog/pull/83
